### ISSUE TITLE
"Too Many Requests" -error when using default rate limiter

### ISSUE THREAD

**Issue by Zentryn** [grantholle/moviedb-promise#17] opened 2019-06-06 15:18 UTC
When using the default rate limiter, the module consistently gives a "Too Many Requests" -error when lots of queries are sent in a quick succession. For example, the following code seems to **always** throw this error after a few seconds:
```
const moviedb = new MovieDB(API_KEY);

for (var i = 0; i < 21; i++) {
    moviedb.searchMovie({ query: "Movie Name" })
        .then(data => {
            console.log(data);
        })
        .catch(err => {
            console.error(err);
        });
}
```

**Comment by rontav** [comment] 2019-06-06 16:18
Duplicate of #16.

**Comment by Zentryn** [comment] 2019-06-06 16:26
Is it really a duplicate? All of the API token requests get throttled by the rate limiter, so the issue described in #16 shouldn't affect this.

**Comment by rontav** [comment] 2019-06-06 16:52
Yeah, you're right, it's not. I thought it's a duplicate because of the code example.
[https://developers.themoviedb.org/3/getting-started/request-rate-limiting](https://developers.themoviedb.org/3/getting-started/request-rate-limiting):
> Our current limits are 40 requests every 10 seconds and are limited by IP address, not API key.

So the current rate limiter isn't the best choice for the job. I'm going to make the lib handle 429 responses since this is what I've did in my app anyways.

**Closed** 2019-06-07 00:53 UTC
